name: Release

on: 
  release:
    types: [created]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        
      - name: Upload artifacts to release
        uses: AButler/upload-release-assets@v3.0
        with:
          files: 'files1/*;files2/p*.json'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
        
